<?php

namespace BusinessLogic\Configuration;

class Configuration
{
    const ENCODE_RESPONSE = "ENCODE_RESPONSE";
    const LOG_CALL_IN_DB = "LOG_CALL_IN_DB";
    const SHOW_PHP_ERRORS = "SHOW_PHP_ERRORS";
    const UPLOAD_PASSWORD = "UPLOAD_PASSWORD";
    const USE_CACHE = "USE_CACHE";
    const SHOW_MLOG = "SHOW_MLOG";
    const GOOGLE_CLIENT_ID = "GOOGLE_CLIENT_ID";
    const GOOGLE_CLIENT_SECRET = "GOOGLE_CLIENT_SECRET";
    const GOOGLE_REDIRECT_URL = "GOOGLE_REDIRECT_URL";
    const EMAIL_SMTP = "EMAIL_SMTP";
    const EMAIL_NAME = "EMAIL_NAME";
    const EMAIL_USERNAME = "EMAIL_USERNAME";
    const EMAIL_PASSWORD = "EMAIL_PASSWORD";
    const EMAIL_RECIPIENTS = "EMAIL_RECIPIENTS";
    const MINIFY_HTML = "MINIFY_HTML";
    const BACKEND_BASE_URL = "BACKEND_BASE_URL";
    const DEFAULT_TIMEZONE = 'DEFAULT_TIMEZONE';
    const NEWS_PATH = 'NEWS_PATH';
    const NETWORK_INTERFACE = 'NETWORK_INTERFACE';
    const GET_WEBSERVICES_URL_ENDPOINT = "GET_WEBSERVICES_URL_ENDPOINT";

}
